
import { ResourceLocation, ResourceType } from './types';

export const MOCK_RESOURCES: ResourceLocation[] = [
  // MUMBAI - SOUTH
  {
    id: 'm-1',
    name: 'Jan Aushadhi Kendra - Colaba',
    type: ResourceType.GOVERNMENT,
    address: 'Near Colaba Post Office, Shahid Bhagat Singh Road',
    city: 'Mumbai',
    region: 'South Mumbai',
    state: 'Maharashtra',
    pincode: '400005',
    coordinates: { lat: 18.915, lng: 72.825 },
    operatingHours: '09:00 AM - 09:00 PM',
    eligibility: ['Open to all', 'Subsidized Suvidha Pads available'],
    requirements: ['None for purchase'],
    contactPhone: '022-22180000',
    verifiedAt: '2024-05-20',
    offersDelivery: false
  },
  {
    id: 'm-2',
    name: 'Myna Mahila Foundation Hub',
    type: ResourceType.NGO,
    address: 'Govandi West, Near Lotus Colony',
    city: 'Mumbai',
    region: 'Central Mumbai',
    state: 'Maharashtra',
    pincode: '400043',
    coordinates: { lat: 19.055, lng: 72.915 },
    operatingHours: '10:00 AM - 06:00 PM',
    eligibility: ['Local women', 'Slum community residents'],
    requirements: ['Self-declaration of need'],
    contactPhone: '+91 9820012345',
    verifiedAt: '2024-05-25',
    offersDelivery: true
  },
  {
    id: 'm-5',
    name: 'Red Dot Foundation - Worli',
    type: ResourceType.NGO,
    address: 'Worli Koliwada, Near Jetty',
    city: 'Mumbai',
    region: 'South Mumbai',
    state: 'Maharashtra',
    pincode: '400030',
    coordinates: { lat: 19.018, lng: 72.815 },
    operatingHours: '10:00 AM - 05:00 PM',
    eligibility: ['Women residents of Worli'],
    requirements: ['ID Proof'],
    contactPhone: '+91 9123456780',
    verifiedAt: '2024-06-01',
    offersDelivery: true
  },
  // MUMBAI - CENTRAL
  {
    id: 'm-3',
    name: 'Dharavi Health Post - Naya Nagar',
    type: ResourceType.GOVERNMENT,
    address: '90 Feet Road, Naya Nagar, Dharavi',
    city: 'Mumbai',
    region: 'Central Mumbai',
    state: 'Maharashtra',
    pincode: '400017',
    coordinates: { lat: 19.040, lng: 72.855 },
    operatingHours: '08:30 AM - 04:30 PM',
    eligibility: ['Adolescent girls', 'Women in child-bearing age'],
    requirements: ['Ration Card (Preferred)'],
    verifiedAt: '2024-05-18',
    offersDelivery: false
  },
  {
    id: 'm-6',
    name: 'SNEHA Center - Dharavi',
    type: ResourceType.NGO,
    address: 'Urban Health Center, Transit Camp',
    city: 'Mumbai',
    region: 'Central Mumbai',
    state: 'Maharashtra',
    pincode: '400017',
    coordinates: { lat: 19.045, lng: 72.860 },
    operatingHours: '09:00 AM - 06:00 PM',
    eligibility: ['Vulnerable women'],
    requirements: ['None'],
    contactPhone: '+91 9000011122',
    verifiedAt: '2024-06-02',
    offersDelivery: true
  },
  {
    id: 'm-4',
    name: 'Project Amara Distribution Center',
    type: ResourceType.NGO,
    address: 'Goregaon East, Aarey Colony Gate 2',
    city: 'Mumbai',
    region: 'Western Suburbs',
    state: 'Maharashtra',
    pincode: '400065',
    coordinates: { lat: 19.165, lng: 72.875 },
    operatingHours: 'Wed/Sat: 11:00 AM - 03:00 PM',
    eligibility: ['Tribal community residents', 'Migrant workers'],
    requirements: ['None'],
    contactPhone: '+91 9930055667',
    verifiedAt: '2024-05-22',
    offersDelivery: true
  },
  // NAVI MUMBAI
  {
    id: 'nm-1',
    name: 'NMMC Health Center - Vashi Sector 10',
    type: ResourceType.GOVERNMENT,
    address: 'Opposite Vashi Plaza, Sector 10',
    city: 'Navi Mumbai',
    region: 'Vashi',
    state: 'Maharashtra',
    pincode: '400703',
    coordinates: { lat: 19.075, lng: 73.001 },
    operatingHours: '09:00 AM - 05:00 PM',
    eligibility: ['Navi Mumbai Residents', 'BPL Card Holders'],
    requirements: ['Identity Proof'],
    contactPhone: '022-27820011',
    verifiedAt: '2024-05-19',
    offersDelivery: false
  },
  {
    id: 'nm-2',
    name: 'Aakar Innovations Hub',
    type: ResourceType.NGO,
    address: 'MIDC Industrial Area, Mahape',
    city: 'Navi Mumbai',
    region: 'Mahape',
    state: 'Maharashtra',
    pincode: '400710',
    coordinates: { lat: 19.115, lng: 73.015 },
    operatingHours: '10:00 AM - 05:00 PM',
    eligibility: ['Industrial labor force women', 'Self-help group members'],
    requirements: ['Work ID or SHG Membership'],
    contactPhone: '+91 8877665544',
    verifiedAt: '2024-05-24',
    offersDelivery: true
  },
  {
    id: 'nm-3',
    name: 'Belapur Urban Health Post',
    type: ResourceType.GOVERNMENT,
    address: 'Sector 15, Near Belapur Station',
    city: 'Navi Mumbai',
    region: 'Belapur',
    state: 'Maharashtra',
    pincode: '400614',
    coordinates: { lat: 19.020, lng: 73.040 },
    operatingHours: '08:00 AM - 02:00 PM',
    eligibility: ['All local residents'],
    requirements: ['Address proof of Navi Mumbai'],
    verifiedAt: '2024-05-21',
    offersDelivery: false
  },
  {
    id: 'nm-4',
    name: 'Sanjeevani NGO Center',
    type: ResourceType.NGO,
    address: 'Kharghar, Sector 12, Pratiksha Tower Ground Floor',
    city: 'Navi Mumbai',
    region: 'Kharghar',
    state: 'Maharashtra',
    pincode: '401021',
    coordinates: { lat: 19.025, lng: 73.065 },
    operatingHours: '09:00 AM - 06:00 PM',
    eligibility: ['Students', 'Low-income families'],
    requirements: ['None'],
    contactPhone: '+91 7766554433',
    verifiedAt: '2024-05-23',
    offersDelivery: true
  },
  {
    id: 'nm-5',
    name: 'Apeksha Foundation - Airoli',
    type: ResourceType.NGO,
    address: 'Airoli, Sector 3, Near Railway Station',
    city: 'Navi Mumbai',
    region: 'Airoli',
    state: 'Maharashtra',
    pincode: '400708',
    coordinates: { lat: 19.155, lng: 72.998 },
    operatingHours: '10:00 AM - 04:00 PM',
    eligibility: ['Domestic workers', 'Security guards'],
    requirements: ['None'],
    contactPhone: '+91 9988776655',
    verifiedAt: '2024-06-05',
    offersDelivery: true
  }
];

export const CITIES = ['Mumbai', 'Navi Mumbai'];
export const REGIONS_BY_CITY: Record<string, string[]> = MOCK_RESOURCES.reduce((acc, curr) => {
  if (!acc[curr.city]) acc[curr.city] = [];
  if (!acc[curr.city].includes(curr.region)) acc[curr.city].push(curr.region);
  return acc;
}, {} as Record<string, string[]>);
